[package]
name = "add-me-bro"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
color-eyre = "0.6.5"
config = "0.15.19"
eyre = "0.6.12"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.0.228", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
