name: Build and Test

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ $default_branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build project
      run: cargo build
    - name: Run tests
      run: cargo test
